### ISSUE TITLE
Missing Requirement : zip

### ISSUE THREAD

**Issue by Badatos** [plgitlogin/premierlangage#1]
In the declared requirements in Readme.md, "zip" is missing.
If not present, it raise an error when launching "install.sh" : 

`zip should be installed. Try 'apt-get install zip'`

**Comment by qcoumes** [comment]
The zip requirement isn't a python module but a system requirement. 

You have to install it on your system before trying to use install.sh ('apt-get install zip' should du the trick on Debian or Ubuntu)

**Comment by Badatos** [comment]
Yes, I know. but i think it could be a good idea to precise the system requirements in the install doc.

**Comment by qcoumes** [comment]
You're right, added to the README.md
