### ISSUE TITLE
Before ne peut pas changer le champs form

### ISSUE THREAD

**Issue by laurent-bulteau** [plgitlogin/premierlangage#10]
Si dans le before on a:
form+="foo"
alors foo devrait s'afficher en bas du formulaire: ce n'est pas le cas.

Bizarrement, si on fait  bar="foo" et qu'on utilise {{bar}} dans le formumlaire, alors ça ça marche (mais via django, donc on ne peut pas insérer directement des balises html)

**Comment by qcoumes** [comment]
Devrait être maintenant corrigé sur master.

**Comment by nimdanor** [comment]
Closed ??
