### ISSUE TITLE
File editing UI: distinct Save and Save&Quit buttons

### ISSUE THREAD

**Issue by nthiery** [plgitlogin/premierlangage#12]
Replace the current Save button by:
- [ ] a Save & Quit button: the current Save
- [ ] a Save button: saves, but remains on the page

Use case: when editing a supporting file `foo` for an exercise, one needs to save `foo` each time one wants to test the exercise (typically using the exercise preview in a separate tab). The current behaviour of saving *and* quitting means that one need to reopen `foo`, and move back to the zone under edition after each test.

**Comment by qcoumes** [comment]
Done
