### ISSUE TITLE
Broken debug download link for the environment

### ISSUE THREAD

**Issue by nthiery** [plgitlogin/premierlangage#122]
Thanks for adding the "Télécharger l'environnement" button to download the environment after the build execution for debugging purposes. It seems that the generated link is broken though:

https://pl-sandbox.u-pem.fr/sandbox/env/test_c0942d5d-a21f-41d2-afbe-427b2fd3f0a6/

Maybe the sandbox is running on a different machine these days?

This is from https://pl.u-pem.fr/filebrowser/home/cpp-info111/exercices/test/opt/?option=entry-direct-edit_pl&target=output.cpp.pl

**Comment by qcoumes** [comment]
Yep, there's wrong with urls and with the filesystem on PL, we'll look into this Monday.

**Comment by qcoumes** [comment]
After a quick check, the URL is correct, but the sandbox is not supposed to be visible on the internet, that's why we're getting this error.
We'll have to redirect the download through PL in order to let the sandbox hidden from the internet.
I'll try to make a little patch to fix this for monday.

**Comment by nthiery** [comment]
Thanks Quentin! Looking forward to that.
Btw: being able to simply print to STDERR to report tracing info is really helpful for debugging. That's a really nice addition.

**Comment by Pavell94000** [comment]
Solved with #124
