### ISSUE TITLE
File editing / preview UI: add git controls

### ISSUE THREAD

**Issue by nthiery** [plgitlogin/premierlangage#13]
Add git controls on the file edit / preview pages; ideally a direct "Pull" button.

Use case: when doing remote edition, transferring the files to PI via git, the edit-test loop is typically:
1.  On PL: Preview the exercise
2.  Local: do some more edition
3.  Local: Push to the repo
4.  On PL: Pull from the repo
5.  Repeat

The less steps the edit loop takes, the the better. Currently step 4. requires to switch to another tab to browse the repo on PL, click on the crank button, click Pull, click Yes to confirm, switch back to the preview tab.

**Comment by nimdanor** [comment]
Yes that the "old" and painfull way. 
The preview editor plus push on external git repository to be safe  is the "new" way.

**Comment by nimdanor** [comment]
can i close ??
