### ISSUE TITLE
Generation of random data in exercises

### ISSUE THREAD

**Issue by ddoyen** [plgitlogin/premierlangage#138]
There is a curious bug with the sympy and random modules in python. Some (non-random) sympy functions change the state of the random generator used by the random module. For instance, in the python script below, the value of the variable c is not the same at each run.

~~~~
import random
import sympy
random.seed(1)
a=random.randint(1,100)
b=random.randint(1,100)
expr=sympy.simplify("x*x-2*x*x")
c=random.randint(1,100)
print(a,b,c)
~~~~

This behavior is problematic when an exercise needs to be played again with the same data. Despite being initialized with the same seed, the random generator produces different data.

So pl exercices should use their own instance of the random generator to produce their random data. Something like :
~~~~
before ==
import random
rd = random.Random()
rd.seed(seed)
a=rd.randint(1,100)
==
~~~~
Instead of :
~~~~
before ==
import random
random.seed(seed)
a=random.randint(1,100)
==
~~~~

**Comment by qcoumes** [comment]
After some research, it happened because Sympy's tests (which are launch automatically) use random.

Using an instance of random seems to be the best thing to do. Thanks for sharing your solution.
We'll add this to the documentation for the version of December.

**Comment by qcoumes** [comment]
I close this issue, since it's not really a bug. Thanks for sharing the solution, we added some information about this in the documentation.
