### ISSUE TITLE
The online editor seems to save end-of-lines in dos-style CRLF format

### ISSUE THREAD

**Issue by nthiery** [plgitlogin/premierlangage#14]
Steps to reproduce:
- Start from a file in one of PL's git repos. Check it out on a Linux machine, and check that the line endings are the standard UNIX's `LF` (`\n`).
- Edit the file using PL's online editor.
- Commit and push
- Pull from Linux

The end of lines are now dos-style  'CRLF' (`\r\n`).

See also `cbank/template/graderC.py` for a file that has `CRLF` end-of-lines, presumably due to this bug; other files in the same repo are not (e.g. the `README,` or `exercices/array/average.pl`)

In principle git is supposed to "do the right thing" and automatically convert end-of-lines according to the local system convention. I suspect that the issue is somewhere between the javascript editor and the server.

**Comment by qcoumes** [comment]
If someone could check this

**Comment by qcoumes** [comment]
Solved on master

**Comment by nthiery** [comment]
>    Solved on master

Thanks!
