### ISSUE TITLE
Standard keyboard shortcuts for navigating the pages and in particular pop-up

### ISSUE THREAD

**Issue by nthiery** [plgitlogin/premierlangage#15]
Example:
- <Tab> / <shift-Tab> to navigate between UI items
- <Enter> to validate a button
- ...

Use case: when clicking on one of the git UI, like `Pull`, one currently needs to move the mouse to click on the Yes button of the confirm pop-up. With the UI, a single Enter would do.

**Comment by qcoumes** [comment]
Can be done with Tab key.
