### ISSUE TITLE
git actions logging

### ISSUE THREAD

**Issue by nthiery** [plgitlogin/premierlangage#18]
When running some git command via the UI, it could be useful to have a log of what was done, in particular if something goes wrong (e.g. a conflict)
- Which git command was run, with which options
- What was its output

This could typically be in some folded-by-default block.

**Comment by nimdanor** [comment]
Elaad can you find someone for this

**Comment by ElaadF** [comment]
Le module que nous utilisons ([gitcmd](https://github.com/qcoumes/gitcmd)]) ne permet pas d'afficher la commande effectué.

**Comment by nimdanor** [comment]
Ok the CLI of git is not used so it's a lot of work to create a pseudo CLI line.

**Comment by qcoumes** [comment]
As said above, [gicmd](https://github.com/qcoumes/gitcmd) does not return the used command, but only outputs.
