### ISSUE TITLE
Make it trivial to fix typos in the documentation

### ISSUE THREAD

**Issue by nthiery** [plgitlogin/premierlangage#19]
Typically by adding a link "edit on github", ...

This will foster crowd-sourcing of the documentation proofreading. Indeed, with a minimum of infrastructure, fixing typos is something that many users -- even non programmers -- can do (possibly after brief training on using pull requests).

**Comment by nimdanor** [comment]
Excellent idea should be implemented rapidely.

**Comment by qcoumes** [comment]
Done
