### ISSUE TITLE
invalid command 'bdist_wheel'

### ISSUE THREAD

**Issue by Badatos** [plgitlogin/premierlangage#2]
When launching "install.sh" dor the first time, an error occures many times :   

error: invalid command 'bdist_wheel'
  
  ----------------------------------------
  Failed building wheel for django-markdown-deux
  Failed building wheel for sympy
  Failed building wheel for yattag
  Failed building wheel for django-bootstrap3
  Failed building wheel for markdown2
... and 8 more.

**Comment by qcoumes** [comment]
Pip should manage to install the requirements without wheel, you can ignore these error.

Have all the requirements been installed correctly despite these errors ?

**Comment by Badatos** [comment]
Maybe...
After all these errors, it ends with "Successfully installed MarkupSafe-1.0 PyYAML-3.12 [.......] hitenoise-3.3.1 yattag-1.10.0
Done !"

then, a warning : "WARNING -  Config value: 'theme_dir'. Warning: The configuration option {0} has been deprecated and will be removed in a future release of MkDocs. "

and then it ask for a super user account, as described in the Readme.

But after that, if you run "python manage.py runserver" :
python: can't open file 'manage.py': [Errno 2] No such file or directory

**Comment by qcoumes** [comment]
It then installed correctly every module, I'll have to look at that wheel error.

From where do run "python manage.py runserver" ?

**Comment by Badatos** [comment]
from where the Readme.md doc says to run it of course ;) (i.e. : the exact same directory we launched "install.sh")
That's the point : maybe it will be a good idea to indicate in it from where we have to launch it. ;)

**Comment by qcoumes** [comment]
OK. The README now tell when its needed to cd.
