### ISSUE TITLE
Internationalisation

### ISSUE THREAD

**Issue by nthiery** [plgitlogin/premierlangage#20]
- Documentation available in English
- Internationalisation of error messages
- ...

**Comment by qcoumes** [comment]
@nimdanor 

Currently French and English are used interchangeably all over the project.

I.E:
* Filebrowser UI in English
* Documentation in French
* Error messages in both
* ...

It would be better to decide whether we should use English or French (without taking future Internationalization and localization into account for now).

**Comment by plgitlogin** [comment]
The rule should be programming stuff should be in English:
	- function name 
	- filename 
	- comments
	-error messages should be internationalized. 
The documentation should be internationalized.so first version in English.

**Comment by qcoumes** [comment]
Ok.
