### ISSUE TITLE
Clickable git url links in Gitload page

### ISSUE THREAD

**Issue by nthiery** [plgitlogin/premierlangage#22]
In the Gitload page, make it easy to access the git repositories themselves (e.g. on github/...) by clicking
on their URL.

Note: already suggested directly to Dominique

**Comment by nimdanor** [comment]
This is not a priority. The reasoning is that the common access to exercises sources should be encouraged and the sharing is done on the pl site it self.  Repository are private.

**Comment by nthiery** [comment]
>    This is not a priority. The reasoning is that the common access to
>    exercises sources should be encouraged and the sharing is done on the
>    pl site it self. Repository are private.

Ok.

This adds another motivation for having direct git access to PL-hosted
repositories.

Cheers,

**Comment by hdouangm** [comment]
It's done.

**Comment by hdouangm** [comment]
https://github.com/plgitlogin/premierlangage/tree/c631801f70ac4de465e8bcb505a6109d56be7b8b
