### ISSUE TITLE
grader.py is a "reserved" module name

### ISSUE THREAD

**Issue by nthiery** [plgitlogin/premierlangage#23]
At first in the cpp-info template directory, I created my support python file for grading under the name "grader.py". But then, the grader key of my pl file was completely ignored. Instead the `grader.py` was executed directly; it seems like my `grader` took precedence over some PL `grader.py` module, though I did not find it in the sources.

No big deal, but it took me some while to figure out I should use a different name. Maybe a note could be added to the documentation? Or a warning issued if a grader.py file exists in the template directory?

**Comment by nimdanor** [comment]
The grader.py filename is effectively reserved. And the doc should explain that the sandbox runs the following process : python3 ./grader.py  
The grader.py file is defined by the  grader key 

grader==
with open("student.py") as stu : 
  # evaluate the student anwser 

print(json.dump(evaluation))
==

**Comment by nimdanor** [comment]
To follow on this the sandbox documentation should be upgraded.

What is the shell command that is executed in the docker, is there a key to define this ?

**Comment by qcoumes** [comment]
Documentation has been update and should now be refered too.
