### ISSUE TITLE
student.py file not created if edition zone is empty

### ISSUE THREAD

**Issue by nthiery** [plgitlogin/premierlangage#24]
I have created an exercise in cpp-info111 using the sandbox as in the cbank/plbank repos. 
I noticed that the "student.py" file does not get created if the edition zone is empty.

However, there may be cases where an empty solution is meaningful. For example, in my case, I am using the edition zone not to write code, but to let the student specify what he thinks the output of the program will be.

No big deal; it's easily worked around.

**Comment by nimdanor** [comment]
The file name should be a parameter so if some one tackle this issue add the posibility to change the filename of the student ACE-edited answer. 
The default value is :

studentfilename=student.py

**Comment by plgitlogin** [comment]
The answer of the student is now inside the JSON containing the answers of the student, the path to this is given as the 2nd argument when calling grader.py (sys.argv[2]).

The grader have to json.load() the file, fetch the answer at the corresponding key ('answer' for `/lib/python/form/editorform.html`) and write to a .py file.

A key exists for every input, even if there's no answer (value is '')

I.E.:
```python3
with open(sys.argv[2]) as f, open('student.py', 'w+') as f2:
    f2.write(json.load(f)['answer'])
```

**Comment by qcoumes** [comment]
The answer of the student is now inside the JSON containing the answers of the student, the path to this is given as the 2nd argument when calling grader.py (sys.argv[2]).

The grader have to json.load() the file, fetch the answer at the corresponding key ('answer' for `/lib/python/form/editorform.html`) and write to a .py file.

A key exists for every input, even if there's no answer (value is '')

I.E.:
```python3
import sys, json

with open(sys.argv[2]) as f, open('student.py', 'w+') as f2:
    f2.write(json.load(f)['answer'])
```
