### ISSUE TITLE
Cool stuff :-)

### ISSUE THREAD

**Issue by nthiery** [plgitlogin/premierlangage#26]
Not really an issue; just a brief report with my recent experience with PL: I have spent about 10 hours reimplenting in PL our WIMS programming exercises. There are of course some rough edges,
and code that could be refactored in retrospect. That was to be expected from such a young project.
But overall it's been pleasant, with both a general design that feels natural, key features (sandboxing, ...) available, and the full support of the standard tools (Python, jinja, git, ...).

Kudos to the whole PL team! We will seriously consider adopting PL for our introductory programming classes in Orsay!

Of course, that's a rather biased judgement from someone with a geek background and specific needs that require some development :-)

I am looking forward further development. As you have seen, I created issues with suggestions for improvements that came up to my mind while using the platform. I hope this helps.

**Comment by nthiery** [comment]
cc: @nimdanor , @nborie, @FlorentHivert

**Comment by nimdanor** [comment]
Thanks from the Team ;)
A lot of work ahead ;)
