### ISSUE TITLE
Editor parameter

### ISSUE THREAD

**Issue by nimdanor** [plgitlogin/premierlangage#27]
The parameters of the editor should be accessible via keys in the pl file.
height width
colortheme etc.

a namespace should be a good idea : 
```
- editor==
key1=12
==
```
or
``` 
editor.key1=12
```
or 
```
editor:key1=12
```
see with quentin witch is best.

**Comment by nimdanor** [comment]
Q peux tu faire faire les modifications du parser à quelqu'un d'autre que toi.

**Comment by nimdanor** [comment]
En particulier afficher la barre d'outils de l'éditeur 👍 
rechercher, substituer changerpolice etc

**Comment by Rafal272** [comment]
Done.

https://github.com/plgitlogin/premierlangage/commit/52bbac94d25b3b1d1b90df43e94ab4995311f952
