### ISSUE TITLE
doc instructions

### ISSUE THREAD

**Issue by Badatos** [plgitlogin/premierlangage#3]
There's a small mistake in the "Deployment" section of the  install doc :

It says :
    Run server/serverpl/install_release.sh

but if you do so directly "./server/serverpl/install_release.sh" it will not work : 

Installing requirements...
Could not open requirements file: [Errno 2] Aucun fichier ou dossier de ce type: 'requirements.txt'

You have to go first in the "server/serverpl/" directory, and only then start "./install_release.sh".

**Comment by qcoumes** [comment]
Added
