### ISSUE TITLE
 leaving page and saving 

### ISSUE THREAD

**Issue by nimdanor** [plgitlogin/premierlangage#30]
When you leave the editor page if the file has been changed you must ask first if the user want to save it or stay on the page.

**Comment by plgitlogin** [comment]
Ok it's work for the editor BUT:
- if no changes where made it should not ask when you leave the page ....
- the change was made directly on the editor with out thinking of the differents usages of the editor

--> now when i change exercices in a sheet it ask's me if a want to leave or not ? is this a bug or a feature, can it be change at the exercice level or the sheet level ??

**Comment by LyZeoN** [comment]
it's a feature.
User can choose to ask for confirmation or not in his settings
https://github.com/plgitlogin/premierlangage/commit/630dbb68c3ce4de0a5659d9a79f632646bc684e5

**Comment by nimdanor** [comment]
Excellent
