### ISSUE TITLE
parser problems 

### ISSUE THREAD

**Issue by nimdanor** [plgitlogin/premierlangage#35]
Dans parsers/pltp.py 
Opérateur += n' existe pas dans les pltp ?? C'est normal ?
Quel est l'opérateur pour le json ?
key%json  ou bien key%=json

je ne comprend pas pourquoi 
== peut être précédé d’espaces dans une fermeture de zone multi ligne ???
je trouve que c'est dangereux est ne doit pas être.

**Comment by Rafal272** [comment]
Done

Opérateur pour le json : 
key%json sur une ligne
key=%json en multi ligne

== ne peut plus être ni précédé ni suivit d'espaces dans une fermeture de zone multi ligne.
