### ISSUE TITLE
Debug data

### ISSUE THREAD

**Issue by plgitlogin** [plgitlogin/premierlangage#38]
Pour être capable de débugger un grader il faut pouvoir exécuter le grader dans son context.
Pour cela il faut être capable de récupérer une archive du répertoire utilisé par la sandbox.
Pour cela il faut dans la view Preview d'un exercice ajouter un bouton permettant le download de cette archive.

**Comment by nthiery** [comment]
>    Pour être capable de débugger un grader il faut pouvoir exécuter le
>    grader dans son context.
>    Pour cela il faut être capable de récupérer une archive du répertoire
>    utilisé par la sandbox.
>    Pour cela il faut dans la view Preview d'un exercice ajouter un bouton
>    permettant le download de cette archive.

+1

In addition it would be helpful, in debug mode, to be able to download
the exercise dictionary in json, as it was just after the build, and
just after the grading. I several times temporarily tweaked the
feedback of the grader to include that information, but it's rather
inconvenient.

Thanks!

**Comment by plgitlogin** [comment]
The archive will have  a file name pl.json  with the pl dictionnairy after the build/before phase  in json format.
import json 
pldic = json.load("pl.json")

**Comment by nthiery** [comment]
>    The archive will have a file name pl.json with the pl dictionnairy
>    after the build/before phase in json format.

Ah right, that part is indeed taken care of already. Perfect. So there
just remains to provide a way to fetch the raw feedback dictionary (in
which the grader could throw additional debug information).

**Comment by qcoumes** [comment]
There's now a button to download the environment in the preview view.
