### ISSUE TITLE
access the local webserver from outside localhost

### ISSUE THREAD

**Issue by Badatos** [plgitlogin/premierlangage#4]
To let people (like me) who want to install premierlangage in a virtual machine environment, maybe it is a good idea to tell them how to launch the server so it will allow connections from others machine than just localhost. 
I think you can do so by starting the server with this command : 

`python manage.py runserver 0.0.0.0:8000`

and also adding your server IP in the "ALLOWED_HOSTS" variable in settings.py

it will allow you to acces the web server even when the server runs on a lightweight VM.

nb : there is still a problem with statics file, but i can't tell if it comes from the above settings. Is there something to do to say the webserver where to find this files ?
* Échec du chargement pour l’élément <script> dont la source est « http://XX.XX.140.247:8000/static/js/jquery_3.1.1.js ».
not_authenticated:27
* Échec du chargement pour l’élément <script> dont la source est « http://XX.XX.140.247:8000/static/js/bootstrap_4.js ».
not_authenticated:29
* Échec du chargement pour l’élément <script> dont la source est « http://XX.XX.140.247:8000/static/js/bootstrap_3.3.7.js ».
not_authenticated:32
* Échec du chargement pour l’élément <script> dont la source est « http://XX.XX.140.247:8000/static/playexo/js/footer.js ».

**Comment by qcoumes** [comment]
Try running the command "python manage.py collectstatic".

Its weird that only the js couldn't be loaded while the css had no problem.

**Comment by Badatos** [comment]
Thank you : the `python manage.py collectstatic` command resolved the missing statics files.

**Comment by Badatos** [comment]
Maybe you can still add the command to launch the server so it will be available outside of localhost in the doc : 

`python manage.py runserver 0.0.0.0:8000`
and also adding your server IP in the "ALLOWED_HOSTS" variable in settings.py
