### ISSUE TITLE
Probleme avec le grader

### ISSUE THREAD

**Issue by nimdanor** [plgitlogin/premierlangage#44]
le code suivant ne fonctione pas il affiche quand on valide une reponse vide : 
0 réussi(s) and 0 ratés sur 0 tests
***Tests validés*** 
ce qui est un peu  problematique ....

<pre>
author=DR
title= Initialisation d'une variable.
tag=variable
text==

Initialisation d'une variable.

	Intialisez la variable X avec la chaine Toto.

==

code==

==

# comme ca cela se passera bien
pltest==
>> X=="Toto"
True
==

template= /python/0PLG/template.pl
</pre>

**Comment by qcoumes** [comment]
Je reçois personnellement

```
Il y a des erreurs dans votre programme.
Erreur dans votre programme:

[Errno 2] No such file or directory: 'student'
```

Ce qui correspond bien aux changement du pull request [#34](https://github.com/plgitlogin/premierlangage/pull/34)

**Comment by qcoumes** [comment]
Le problème vient du fait qu'il manque un '>' dans le pltest.

Mais il y a toujours le problème que le feedback affiche "Test Réussie" quand une exception à lieu.
