### ISSUE TITLE
Randomisation is strange 

### ISSUE THREAD

**Issue by nimdanor** [plgitlogin/premierlangage#54]
Le fonctionnement de la gestion de la seed pour les exercices aléatoires n'est pas très claire.

Que faut il faire pour conserver la seed tant que l’élève n'a pas bien répondu ?
Que faut il faire pour réinitialiser la seed a chaque essai ? (reussi ou rate) et dans ce cas la comment fit on dans evaluator pour récupérer la seed ??

Doit on utiliser une activité si oui comment ??

**Comment by qcoumes** [comment]
Tiré de la documentation:

___________

## Variables Aléatoires
Lors de la première ouverture d'un exercice par un élève, une *seed* (actuellement *time.time()*, qui est le nombre de seconde écoulée depuis 01/01/1970) est automatiquement généré par la plateforme. Cette *seed* est accessible n'importe où dans l'exercice grâce à la variable **seed** et doit donc être utilisée pour initialiser le module *random* afin que l'exercice reste identique une fois généré pour un élève.

Si vous souhaiter que la *seed* soit régénérée à chaque fois que l'on charge l'exercice ajouter la balise *oneshot=True* dans votre pl. 

Pour initialiser le module random avec la *seed*, il suffit d'ajouter au début du script *before*:
```python
import random
random.seed(seed)

[...]
```

**Comment by nimdanor** [comment]
OK Houston nous avons un probleme
Le probleme c'est que before semble ^etre execute deux fois
 et donc nous avons besoin de savoir si l'on est dans un before ou un before + evaluator ?? 

Premiere possibilite : pas de relance de before => problem les valeurs non serialisable necessaire dans evaluator. 

Deuxieme possibilite :  une option qui permet de decider si l'on relance ou pas before ??? 

Troisieme possibilite : Donc une variable qui indique si l'on est dans le premier ou deuxieme before ?


Quatrieme possiblite :  Une variable qui nous indique le numéro de la tentative de  l'eleve fait l'exercice (oneshot on compte le nombre d'essai, oneshot=False on compte le nombre de fois ou l'exercice a été bien réussi). 
j'aime bien cette possibilite, ainsi je peux savoir ce que je doit faire dans before : 
je fait random.seed(seed+tentative) MAIS il ne faut pas que tentative soit incremente entre les deux evaluation de before ..... sinon on revient a l case precedente.

**Comment by nimdanor** [comment]
Bon 
j'ai réglé dans master le problem de seed:
si première fois ou un nouvelle version de l'exercice ou si oneshot la seed est régénérée.  
Reste le compteur d'essais.

**Comment by nimdanor** [comment]
Le dernier problème était un problem de bouton de rafraichessement qui n'apparaisait plus.
