### ISSUE TITLE
Edit and preview not on the same file

### ISSUE THREAD

**Issue by nimdanor** [plgitlogin/premierlangage#57]
Comme on peut voire sur le screen shot suivant le titre contient "II" 
mais pas le titre dans la preview, ceci est obtenu après avoir modifie quelque chose dans le fichier (une ligne vide de plus) et clicker sur preview . 
Pour obtenir cette situation j'ai ouvert deux exos différents dans l’éditeur.

https://screenshots.firefox.com/VDmppSnfHqR1wIfM/127.0.0.1

**Comment by qcoumes** [comment]
C'était qu'elle exercice, l'autre ouvert ?

**Comment by nimdanor** [comment]
les exercices /concept/values/calculmystere*.pl

**Comment by nimdanor** [comment]
https://github.com/nimdanor/python-pl-bank/blob/master/concept/value/calculmystere.pl

**Comment by qcoumes** [comment]
Ça ne devrait plus arriver. (ne pas hésiter à rouvrir dans le cas contraire)
