### ISSUE TITLE
Problem de transmission a la sandbox : variables perdues 

### ISSUE THREAD

**Issue by nimdanor** [plgitlogin/premierlangage#59]
je fait l'exo 
https://github.com/nimdanor/python-pl-bank/blob/master/concept/round/foobar.pl
je propose une solution 
def f():
    return 4
et puis je vais dans tmp et j'execute le script suivant : 

   import json 
   pl = json.load(open("pl.json"))
   print(pl.keys())
   print(pl["text"]) 
   print(pl["pltest"])

et j'obtiens : 
dict_keys(['__format', '__rel_path', '__comment', '__dependencies', '__extends', 'title', 'before', 'grader', 'form', 'seed'])
Traceback (most recent call last):
  File "debug.py", line 9, in <module>
    print(pl["text"])
KeyError: 'text'

ce qui me pose un probleme  c'est que la clef text a disparue 
[ plus grave c'est quand c'est la clef pltest qui me permet d'evaluer l'exercice]

 

Il faudrait qu'un test  vérifie ce type de problemes. .....

**Comment by qcoumes** [comment]
Donc c'est pas forcément la clef *text* qui manque ? Ça arrive aléatoirement sur n'importe qu'elle clef ?

**Comment by qcoumes** [comment]
Ça arrive toujours avec la nouvelle sandbox ?
