### ISSUE TITLE
Useless parameter in evaluator.call()

### ISSUE THREAD

**Issue by nimdanor** [plgitlogin/premierlangage#65]
The test parameter in the evaluator.call() method of Sandbox in playexo seem to be useless.
See FIXME in code

**Comment by qcoumes** [comment]
No it's not, its sent alongside the build request (if the environment was not found and need to be rebuilt) to build a testing environment.

**Comment by nimdanor** [comment]
Can it be used to call build again to change the exercice ?

**Comment by qcoumes** [comment]
Not really, why would you change the exercise when calling the evaluator?

**Comment by nimdanor** [comment]
Because a want to do a multi step exercise.
Or an exercise where I can give a hint if the first answer is erroneous .

**Comment by qcoumes** [comment]
You can modify the context in your grader, that's the purpose of the 3rd argument.

**Comment by nimdanor** [comment]
So I can change the text the student will see  ?
