### ISSUE TITLE
ecrire_pl doc avec home:

### ISSUE THREAD

**Issue by nimdanor** [plgitlogin/premierlangage#74]
IL reste des références à la syntaxe home: dans ecrire_pl.md

il serait bon de faire un point global sur les références dans un fichier de documentation 
spécifique et faire référence partout a ce fichier.

**Comment by plgitlogin** [comment]
Ouais tu push maintenant parce que j’était pas au courant et donc je modifiais master …

**Comment by qcoumes** [comment]
Non, j'ai modifié des formulaires, grader et builders en même temps, et ce n'est ni finis, ni testé.

Je l'avais dit lundi...

**Comment by qcoumes** [comment]
Je vous l'ai dit lundi.

Les images sont dans ce dossier:
https://github.com/plgitlogin/premierlangage/tree/update_doc/server/serverpl/documentation/mkdocs/docs/images

**Comment by qcoumes** [comment]
update_doc merged on master

You may want to use `./serverpl/install/make_doc.sh` from the same directory as manage.py to rebuild the documentation
