### ISSUE TITLE
Syntaxe des variables 

### ISSUE THREAD

**Issue by nimdanor** [plgitlogin/premierlangage#75]
Dans la doc il y a marqué que la syntax pour avoir des variables du pl dans le formulaire c'est :
```
form==
<input type="checkbox" id="form_langage" value="{% templatetag openvariable %} l1 {% templatetag closevariable %}"> {% templatetag openvariable %} l1 {% templatetag closevariable %}</input>
...
==
```
Quelle est la différence avec la syntaxe : 
```
form==
<input type="checkbox" id="form_langage" value="{{ l1 }}"> {{ l1 }}</input>
...
==
```
Qui me semble plus courte et plus lissible ??

**Comment by qcoumes** [comment]
`{% templatetag openvariable %} l1 {% templatetag closevariable %}`

Sera interprété en `{{ l1 }}` à l'affichage de la doc.

C'est le moyen d'échapper {{ et }} dans un template

https://docs.djangoproject.com/en/2.1/ref/templates/builtins/#templatetag
