### ISSUE TITLE
Balise multiligne commencant par un retour chariot

### ISSUE THREAD

**Issue by nimdanor** [plgitlogin/premierlangage#76]
La balise code commence toujours dans le cas multi-ligne par un caractère \n
ce qui fait que le code commence toujours par une ligne vide.
je pense que ce caractère est inutile dans les valeurs multi-ligne.
Sachant qu'il n'est pas permis de placer des informations sur la première ligne comme dans l'edxemple suivant 
``` 
    code== coucou
    toto
    ==
```

**Comment by qcoumes** [comment]
Le problème vient du formulaire. Cela n'arrive plus avec le formulaire `/form/text_editor.html`

Pour la documentation du formulaire: Documentation -> Formulaire -> Éditeur de texte
