### ISSUE TITLE
Dépots à cloner uniquement sur la racine de l'explorateur de fichier dans Gitload

### ISSUE THREAD

**Issue by mciissee** [plgitlogin/premierlangage#77]
Quand on met un dossier dans un sous-dossier git il ne trouve pas la référence

**Comment by qcoumes** [comment]
@nimdanor 

Du coup, les repos peuvent être n'importe où ou simplement à la racine du home ?

**Comment by nimdanor** [comment]
@qcoumes
Moi j’ai rien conte el fait qu’ils soit n’importe ou mais je crois que tu auras moins de mal à écrire le code si c’est seulement à la racine de home.

Pour le moment je propose de juste placer les repos à la racine et que tout de façon a terme on trouve une autre solution
Global à la quelle nous devons réfléchir,
En écrivant toutes les contraintes.
