### ISSUE TITLE
before.py -> default .py

### ISSUE THREAD

**Issue by qcoumes** [plgitlogin/premierlangage#78]
@nimdanor 

Pourquoi avoir renommer le builder `before.py` en `default.py` (commit [5846dc152](https://github.com/plgitlogin/premierlangage/commit/5846dc1522750722e4e8811eb8ee9304be4bcade)) ?

**Comment by qcoumes** [comment]
@nimdanor Je peux supprimer ce default.py ?

**Comment by plgitlogin** [comment]
OUI
