### ISSUE TITLE
Le menu déroulant se cache derrière le contenu

### ISSUE THREAD

**Issue by laurent-bulteau** [plgitlogin/premierlangage#8]
Quand la fenêtre n'est pas assez large, la barre du haut devient un menu déroulant, qui  passe derrière le contenu de la page quand on le déroule (par exemple dans l'explorateur de fichiers)

**Comment by qcoumes** [comment]
Je viens de corriger ça, et par la même occasion pusher une version plus récente sur Github.

Cette nouvelle version aura peut être des conflit avec l'ancienne version de la base de données.
Le script *premierlangage/server/serverpl* corrigera ces problèmes mais videra la base de données.
